package ferramentoteca.view;

import ferramentoteca.Usuario;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JPanel;

public class TelaMenuPrincipal extends javax.swing.JFrame {

    private Usuario usuarioLogado;

    public TelaMenuPrincipal(Usuario usuario) {

        this.usuarioLogado = usuario;
        initComponents();
        configurarPermissoes();

        jPanelMenu.setLayout(new GridLayout(2, 2, 20, 20));
        setPreferredSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(800, 600));
        setSize(800, 600);

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jPanelInventario = new javax.swing.JPanel();
        btnInventario = new javax.swing.JButton();
        jPanelCadastroFerramenta = new javax.swing.JPanel();
        btnCadastroF = new javax.swing.JButton();
        jPanelCadastroUsuario = new javax.swing.JPanel();
        bntCadastroUsuario = new javax.swing.JButton();
        jPanelEmprestimo = new javax.swing.JPanel();
        btnEmprestimos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setSize(new java.awt.Dimension(1440, 1024));

        jPanelMenu.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        jPanelInventario.setBackground(new java.awt.Color(0, 102, 255));

        btnInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInventario.setText("INVENTÁRIO");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInventarioLayout = new javax.swing.GroupLayout(jPanelInventario);
        jPanelInventario.setLayout(jPanelInventarioLayout);
        jPanelInventarioLayout.setHorizontalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnInventario)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanelInventarioLayout.setVerticalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnInventario)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelInventario);

        jPanelCadastroFerramenta.setBackground(new java.awt.Color(102, 102, 255));

        btnCadastroF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastroF.setText("CADASTRO DE FERRAMENTAS");
        btnCadastroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroFerramentaLayout = new javax.swing.GroupLayout(jPanelCadastroFerramenta);
        jPanelCadastroFerramenta.setLayout(jPanelCadastroFerramentaLayout);
        jPanelCadastroFerramentaLayout.setHorizontalGroup(
            jPanelCadastroFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroFerramentaLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnCadastroF)
                .addGap(67, 67, 67))
        );
        jPanelCadastroFerramentaLayout.setVerticalGroup(
            jPanelCadastroFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFerramentaLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnCadastroF)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelCadastroFerramenta);

        jPanelCadastroUsuario.setBackground(new java.awt.Color(0, 204, 255));

        bntCadastroUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCadastroUsuario.setText("CADASTRO DE USUARIOS");
        bntCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastroUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroUsuarioLayout = new javax.swing.GroupLayout(jPanelCadastroUsuario);
        jPanelCadastroUsuario.setLayout(jPanelCadastroUsuarioLayout);
        jPanelCadastroUsuarioLayout.setHorizontalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bntCadastroUsuario)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelCadastroUsuarioLayout.setVerticalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(bntCadastroUsuario)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelCadastroUsuario);

        jPanelEmprestimo.setBackground(new java.awt.Color(51, 0, 204));

        btnEmprestimos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmprestimos.setText("EMPRESTÍMOS");
        btnEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmprestimoLayout = new javax.swing.GroupLayout(jPanelEmprestimo);
        jPanelEmprestimo.setLayout(jPanelEmprestimoLayout);
        jPanelEmprestimoLayout.setHorizontalGroup(
            jPanelEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmprestimoLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(btnEmprestimos)
                .addGap(121, 121, 121))
        );
        jPanelEmprestimoLayout.setVerticalGroup(
            jPanelEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmprestimoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnEmprestimos)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelEmprestimo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        new TelaInventario().setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnCadastroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFActionPerformed
        new TelaCadastroFerra().setVisible(true);
    }//GEN-LAST:event_btnCadastroFActionPerformed

    private void btnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimosActionPerformed
        new TelaEmprestimo(usuarioLogado).setVisible(true);
    }//GEN-LAST:event_btnEmprestimosActionPerformed

    private void bntCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastroUsuarioActionPerformed
        new TelaCadastroUsuario().setVisible(true);
    }//GEN-LAST:event_bntCadastroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    private void configurarPermissoes() {
        String tipo = usuarioLogado.getTipo();

        if (tipo.equals("Administrador")) {
            // Acesso total
        } else if (tipo.equals("Operador")) {
            bntCadastroUsuario.setVisible(false);  // Não pode cadastrar usuário
        } else if (tipo.equals("Visualizador")) {
            bntCadastroUsuario.setVisible(false);
            btnCadastroF.setVisible(false);
            btnEmprestimos.setVisible(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastroUsuario;
    private javax.swing.JButton btnCadastroF;
    private javax.swing.JButton btnEmprestimos;
    private javax.swing.JButton btnInventario;
    private javax.swing.JPanel jPanelCadastroFerramenta;
    private javax.swing.JPanel jPanelCadastroUsuario;
    private javax.swing.JPanel jPanelEmprestimo;
    private javax.swing.JPanel jPanelInventario;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
