package ferramentoteca.view;

import ferramentoteca.EmprestimoDAO;
import ferramentoteca.Emprestimo;
import ferramentoteca.Ferramenta;
import ferramentoteca.FerramentaDAO;
import ferramentoteca.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class TelaEmprestimo extends javax.swing.JFrame {

    private Ferramenta ferramentaSelecionada;

    private Usuario usuarioLogado;

    public TelaEmprestimo(Usuario usuarioLogado) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioLogado = usuarioLogado;  
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdNome = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelLocalizacao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomeProfessor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFieldDataEmprestimo = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFieldDataDevolucao = new javax.swing.JFormattedTextField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emprestímo");
        setSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 656));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("EMPRESTÍMO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID ou Nome de Ferramenta: ");

        txtIdNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdNome.setForeground(new java.awt.Color(0, 0, 0));
        txtIdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNomeActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("[ Mostra-se apenas se a ferramenta estiver disponível.  ]");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDescricao.setText("Descrição:");

        jLabelLocalizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLocalizacao.setText("Localização:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLocalizacao)
                    .addComponent(jLabelDescricao)
                    .addComponent(jLabelNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLocalizacao)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Dados para cadastrar emprestímo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Professor: ");

        txtNomeProfessor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeProfessor.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfessorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Data do Emprestímo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Data de Devolução:");

        txtFieldDataDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDataDevolucaoActionPerformed(evt);
            }
        });

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar.setText("Confirmar Emprestímo");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFieldDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnConfirmar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNomeActionPerformed

    }//GEN-LAST:event_txtIdNomeActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = txtIdNome.getText().trim();

        if (criterio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um ID ou nome para buscar",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            FerramentaDAO dao = new FerramentaDAO();
            Ferramenta ferramenta = dao.buscarParaEmprestimo(criterio);

            if (ferramenta == null) {
                JOptionPane.showMessageDialog(this, "Ferramenta não encontrada",
                        "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limparDadosFerramenta();
                return;
            }

           
            if (ferramenta.getStatus().equalsIgnoreCase("Desativada")) {
                JOptionPane.showMessageDialog(this, "Esta ferramenta se encontra desativada",
                        "Status", JOptionPane.WARNING_MESSAGE);
                limparDadosFerramenta();
                return;
            }

            if (ferramenta.getStatus().equalsIgnoreCase("Emprestada")) {
                JOptionPane.showMessageDialog(this, "Esta ferramenta está emprestada",
                        "Status", JOptionPane.INFORMATION_MESSAGE);
                limparDadosFerramenta();
                return;
            }

          
            mostrarDadosFerramenta(ferramenta);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro na busca: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarDadosFerramenta(Ferramenta ferramenta) {
        jLabelNome.setText("Nome: " + ferramenta.getNome());
        jLabelDescricao.setText("Descrição: " + ferramenta.getDescricao());
        jLabelLocalizacao.setText("Localização: " + ferramenta.getLocalizacao());

        // Habilita o botão de confirmar empréstimo
        btnConfirmar.setEnabled(true);
        ferramentaSelecionada = ferramenta; // Guarda a referência para usar no empréstimo
    }

    private void limparDadosFerramenta() {

        jLabelNome.setText("Nome: ");
        jLabelDescricao.setText("Descrição: ");
        jLabelLocalizacao.setText("Localização: ");

        btnConfirmar.setEnabled(false);
        ferramentaSelecionada = null;

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfessorActionPerformed
     
    }//GEN-LAST:event_txtNomeProfessorActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (ferramentaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Nenhuma ferramenta selecionada!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String professorNome = txtNomeProfessor.getText().trim();
        String dataEmprestimoStr = txtFieldDataEmprestimo.getText().trim();
        String dataDevolucaoStr = txtFieldDataDevolucao.getText().trim();

        if (professorNome.isEmpty() || dataEmprestimoStr.isEmpty() || dataDevolucaoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");  

        try {
            java.util.Date utilDataEmprestimo = sdf.parse(dataEmprestimoStr);
            java.util.Date utilDataDevolucao = sdf.parse(dataDevolucaoStr);

            java.sql.Date dataEmprestimo = new java.sql.Date(utilDataEmprestimo.getTime());
            java.sql.Date dataDevolucao = new java.sql.Date(utilDataDevolucao.getTime());

            Emprestimo emprestimo = new Emprestimo(
                    0, 
                    this.usuarioLogado.getId(), 
                    ferramentaSelecionada.getId(), 
                    professorNome, 
                    utilDataEmprestimo, 
                    utilDataDevolucao, 
                    "Emprestado" 
            );

            
            EmprestimoDAO dao = new EmprestimoDAO();
            dao.registrarEmprestimo(emprestimo);

          
            ferramentaSelecionada.setStatus("Emprestada");
            FerramentaDAO fdao = new FerramentaDAO();
            fdao.atualizar(ferramentaSelecionada);

            JOptionPane.showMessageDialog(this, "Empréstimo registrado com sucesso!");

            limparCampos();

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido! Use: yyyy-MM-dd",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar empréstimo: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed
    private void limparCampos() {
        txtNomeProfessor.setText("");
        txtFieldDataEmprestimo.setText("");
        txtFieldDataDevolucao.setText("");

        
        ferramentaSelecionada = null;

    }


    private void txtFieldDataDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDataDevolucaoActionPerformed
      
    }//GEN-LAST:event_txtFieldDataDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelLocalizacao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txtFieldDataDevolucao;
    private javax.swing.JFormattedTextField txtFieldDataEmprestimo;
    private javax.swing.JTextField txtIdNome;
    private javax.swing.JTextField txtNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
