package ferramentoteca.view;

import java.sql.SQLException;
import ferramentoteca.Emprestimo;
import ferramentoteca.EmprestimoDAO;
import ferramentoteca.Ferramenta;
import ferramentoteca.FerramentaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaInventario extends javax.swing.JFrame {

    public TelaInventario() {
        initComponents();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelInventario = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabelLocalizacao = new javax.swing.JLabel();
        jComboBoxLoca = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jLabelPreencha = new javax.swing.JLabel();
        jLabelTodosOs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnLimparFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventário");
        setSize(new java.awt.Dimension(1440, 1024));

        jLabelInventario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelInventario.setText("INVENTÁRIO");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNome.setText("Nome: ");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelStatus.setText("Status:");

        jComboBoxStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Disponível", "Emprestada", "Desativada" }));

        jLabelLocalizacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelLocalizacao.setText("Localização:");

        jComboBoxLoca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxLoca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Estante", "Arquivo", "Oficina", "Caixa de ferramentas" }));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabelPreencha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelPreencha.setText("Preencha um ou mais filtros para buscar. ");

        jLabelTodosOs.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelTodosOs.setText("Todos os filtros são opcionais.");

        jTable.setBackground(new java.awt.Color(153, 153, 153));
        jTable.setModel(montarTabela());
        jScrollPane1.setViewportView(jTable);

        btnLimparFiltros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimparFiltros.setText("Limpar Filtros");
        btnLimparFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelLocalizacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelPreencha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelTodosOs)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelStatus)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelNome)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabelInventario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(btnLimparFiltros)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelInventario)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(jLabelLocalizacao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreencha)
                    .addComponent(jLabelTodosOs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimparFiltros)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nomeFiltro = txtNome.getText().trim();
        String statusFiltro = jComboBoxStatus.getSelectedItem().toString();
        String localFiltro = jComboBoxLoca.getSelectedItem().toString();

        if (nomeFiltro.isEmpty()
                && statusFiltro.equalsIgnoreCase("Selecione uma opção")
                && localFiltro.equalsIgnoreCase("Selecione uma opção")) {
            JOptionPane.showMessageDialog(this, "Preencha pelo menos um filtro para buscar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel tabela = (DefaultTableModel) jTable.getModel();
        tabela.setRowCount(0); // limpa a tabela

        try {
            FerramentaDAO ferramentaDAO = new FerramentaDAO();
            EmprestimoDAO emprestimoDAO = new EmprestimoDAO();

            List<Ferramenta> ferramentas = ferramentaDAO.listarTodos();

            for (Ferramenta f : ferramentas) {
                boolean atendeNome = nomeFiltro.isEmpty() || f.getNome().toLowerCase().contains(nomeFiltro.toLowerCase());
                boolean atendeStatus = statusFiltro.equalsIgnoreCase("Selecione uma opção") || f.getStatus().equalsIgnoreCase(statusFiltro);
                boolean atendeLocal = localFiltro.equalsIgnoreCase("Selecione uma opção") || f.getLocalizacao().equalsIgnoreCase(localFiltro);

                if (atendeNome && atendeStatus && atendeLocal) {
                    Emprestimo emprestimo = emprestimoDAO.buscarEmprestimoAtivoPorFerramenta(f.getId());

                    String dataDevolucao = emprestimo != null
                            ? emprestimo.getDataDevolucaoFormatada() : "";

                    String responsavel = emprestimo != null ? emprestimo.getResponsavel() : "";

                    String motivoDesativacao = "";
                    if (f.getStatus().equalsIgnoreCase("Desativada")) {
                        motivoDesativacao = f.getMotivoDesativacao();
                    }

                    String[] linha = {
                        String.valueOf(f.getId()),
                        f.getNome(),
                        f.getStatus(),
                        f.getLocalizacao(),
                        dataDevolucao,
                        responsavel,
                        motivoDesativacao
                    };

                    tabela.addRow(linha);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar ferramentas: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltrosActionPerformed
        // Limpa os campos de filtro
        txtNome.setText("");
        jComboBoxStatus.setSelectedIndex(0); 
        jComboBoxLoca.setSelectedIndex(0);   

        // Recarrega a tabela com todos os dados
        DefaultTableModel modeloTabela = montarTabela();
        jTable.setModel(modeloTabela);
    }//GEN-LAST:event_btnLimparFiltrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInventario().setVisible(true);
            }
        });
    }

    private DefaultTableModel montarTabela() {
        String[] colunas = {
            "ID", "Nome", "Status", "Localização", "Data de Devolução", "Responsável", "Motivo da desativação"
        };
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        try {
            FerramentaDAO ferramentaDAO = new FerramentaDAO();
            EmprestimoDAO emprestimoDAO = new EmprestimoDAO();

            List<Ferramenta> ferramentas = ferramentaDAO.listarTodos();

            for (Ferramenta f : ferramentas) {
                Emprestimo emprestimo = emprestimoDAO.buscarEmprestimoAtivoPorFerramenta(f.getId());

                String dataDevolucao = emprestimo != null
                        ? emprestimo.getDataDevolucaoFormatada() : "";

                String responsavel = emprestimo != null ? emprestimo.getResponsavel() : "";

                String motivoDesativacao = "";
                if (f.getStatus().equalsIgnoreCase("Desativada")) {
                    motivoDesativacao = f.getMotivoDesativacao();
                }

                String[] linha = {
                    String.valueOf(f.getId()),
                    f.getNome(),
                    f.getStatus(),
                    f.getLocalizacao(),
                    dataDevolucao,
                    responsavel,
                    motivoDesativacao
                };

                tabela.addRow(linha);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados do inventário: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

        return tabela;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimparFiltros;
    private javax.swing.JComboBox<String> jComboBoxLoca;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabelInventario;
    private javax.swing.JLabel jLabelLocalizacao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreencha;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTodosOs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
